Repository puppetlabs/puppetlabs-exec, pull requests merged in 2019-11, with the labels that each got.

#97 pdksync - (FM-8634) ensure encrypted communication for fixtures
  .fixtures.yml
Labels: maintenance

#99 pdksync - FM-8499 - remove ubuntu14 support
  metadata.json
  provision.yaml
Labels: backwards-incompatible

#101 (FM-8687) - Addition of Support for CentOS 8
  metadata.json
  provision.yaml
Labels: feature

#102 (MODULES-10103) - Release Merge back v0.6.0
  CHANGELOG.md
  metadata.json
Labels: maintenance

#104 (MODULES-10120) enable simplecov; update to PDK 1.14.1; minor cleanups
  .gitignore
  .pdkignore
  .project
  .sync.yml
  .travis.yml
  Gemfile
  appveyor.yml
  metadata.json
Labels: maintenance
